"""
Eduardo Sosa, Tony Zeng, Sal Balkus, Nidhi Pai
Aerospace Team
"""

import numpy as np
from scipy.stats import chi2

class Distances:
    """
    Just calculates various distances

    Methods tagged with threshold means that it takes in a thresold and returns True if the dis is < threshold
    Measurement is a column vector and kfilter is a filter
    """
    @staticmethod
    def euclidean(measurement, kfilter):
        """
        Calculates the Euclidean distance between the measurement and the current estimate.

        Args:
            measurement (ndarray): The measurement generated by the sensor.
            kfilter (KalmanFilter): The kalman filter. 

        Returns:
            (float): The Euclidean distance. 

        """
        return np.linalg.norm(measurement - kfilter.get_current_guess())

    @staticmethod
    def mahalanobis(measurement, kfilter):
        """
        Calculates the Mahalanobis distance between the measurement and the current estimate.

        Args:
            measurement (ndarray): The measurement generated by the sensor.
            kfilter (KalmanFilter): The kalman filter. 

        Returns:
            (float): The Mahalanobis distance. 

        """
        innovation = measurement - kfilter.h(kfilter.x_hat_minus)
        K = kfilter.H @ kfilter.P_minus @ kfilter.H.T + kfilter.R
        dis = np.sqrt(innovation.T @ np.linalg.inv(K) @ innovation)
        dis = dis[0][0]  # this is kinda hacky and the fact that I have to do this may signal that something is wrong
        return dis

    @staticmethod
    def euclidean_threshold(measurement, kfilter, error_threshold):
        """
        Returns whether the Euclidean distance between the measurement and the current a posteriori estimate
        is below the given error threshold. 

        Args:
            measurement (ndarray): The measurement generated by the sensor.
            kfilter (KalmanFilter): The kalman filter. 
            error_threshold (float): A float indicating the error threshold. 

        Returns:
            (bool): True or False depending on whether the distance is less than threshold. 

        """
        dis = Distances.euclidean(measurement, kfilter)
        return dis < error_threshold

    @staticmethod
    def mahalanobis_threshold(measurement, kfilter, error_threshold):
        """
        Returns whether the Mahalanobis distance between the measurement and the current a posteriori estimate
        is below the given error threshold. 

        Args:
            measurement (ndarray): The measurement generated by the sensor.
            kfilter (KalmanFilter): The kalman filter. 
            error_threshold (float): A float indicating the error threshold. 

        Returns:
            (bool): True or False depending on whether the distance is less than threshold. 
        """

        dis = Distances.mahalanobis(measurement, kfilter)
        cutoff = chi2.ppf(error_threshold, 2)
        return dis < cutoff

